name: robojax
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  # basics
  - python=3.8
  - numpy
  - matplotlib
  - dill
  - pandas
  - seaborn
  - scipy
  - jupyterlab
  - pip
  - ipdb
  - cython
  - scikit-learn
  - tqdm
  - yaml
  - ipywidgets
  - black
  - isort

  # RL related
  - gym

  - huggingface::transformers

  # Vision
  - opencv
  - transforms3d

  - pip:
    # Jax ecosystem
    - jax[cpu]
    - chex
    # - haiku
    - flax
    - distrax
    - optax

  #   # Simulators
    - mujoco-py<2.2,>=2.1

  #   # Video generation
    - moviepy

  #   # Exp tracking
    - tensorboard
    - wandb
    - omegaconf

  #   # More Deep Learning
    - huggingface_hub
    
    - pyglet>=1.4.0

  #   # More RL
    - stable-baselines3