jax_env: True

seed: 0
algo: ppo

# Environment configuration
env:
  env_id: "ant"
  max_episode_steps: 1000
eval_env:
  max_episode_steps: 1000

ppo:
  batch_size: 2048
  num_envs: 4096
  steps_per_env: 32
  grad_updates_per_step: 128
  reset_env: False # Important to set to False to leverage massive parallelization properly

  target_kl: 1
  discount: 0.97
  ent_coef: 1e-2

  eval_freq: 5_000_000
  eval_steps: 1_000
  num_eval_envs: 64

  log_freq: 1_000
  save_freq: -1
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

train:
  steps: 100_000_000

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"