env_id: HalfCheetah-v3
jax_env: False
auto_reset: True

jax_platform_name: gpu

seed: 0

sac:
  # num_seed_steps: 2_500
  num_seed_steps: 10_000
  num_train_steps: 1_000_000
  # replay_buffer_capacity: 250_000
  replay_buffer_capacity: 1_000_000
  batch_size: 256
  # num_envs: 4
  num_envs: 1
  steps_per_env: 1

  eval_freq: 5000
  eval_steps: 1000
  num_eval_envs: 4

  log_freq: 1000

  learnable_temp: True
  initial_temperature: 1.0

  max_episode_length: 1000
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "sac/halfcheetah"
  wandb_cfg:
    group: "benchmark"