env_id: hopper
jax_env: True
auto_reset: True

jax_platform_name: gpu

seed: 0

sac:
  num_seed_steps: 4096
  num_train_steps: 6_553_600
  replay_buffer_capacity: 32768 
  #1_048_576

  # num_envs: 128
  batch_size: 1024
  # update_iters: 32
  
model:
  actor_lr: 3e-4
  critic_lr: 4e-4
 

train:
  num_envs: 128
  update_iters: 32
  epochs: 600
  steps_per_epoch: 256

eval:
  num_eval_envs: 16
  steps_per_env: 1000 # one episode each
  eval_freq: 20


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "ppo/hopper_short"
  wandb_cfg:
    group: "benchmark"