env_id: hopper
jax_env: true
auto_reset: True

jax_platform_name: gpu

seed: 0

sac:
  num_seed_steps: 10_000
  num_train_steps: 100_000
  replay_buffer_capacity: 100_000

  # num_envs: 128
  batch_size: 256
  # update_iters: 32

  eval_freq: 5000
  eval_steps: 1000
  num_eval_envs: 4

  log_freq: 1000

  learnable_temp: True
  initial_temperature: 1.0

  max_episode_length: 1000
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4
 

train:
  num_envs: 1
  update_iters: 32
  epochs: 600
  steps_per_epoch: 256

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "sac/hopper"
  wandb_cfg:
    group: "benchmark"