env_id: Hopper-v3
jax_env: False
auto_reset: True

jax_platform_name: gpu

seed: 0

sac:
  num_seed_steps: 10_000
  num_train_steps: 6_553_600
  replay_buffer_capacity: 1_000_000

  # num_envs: 128
  batch_size: 256
  # update_iters: 32

  eval_freq: -1
  log_freq: 1000

  learnable_temp: True
  initial_temperature: 1.0
  
model:
  actor_lr: 3e-4
  critic_lr: 4e-4
 

train:
  num_envs: 1
  update_iters: 32
  epochs: 600
  steps_per_epoch: 256

eval:
  num_eval_envs: 16
  steps_per_env: 1000 # one episode each
  eval_freq: 20


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "sac/hopper"
  wandb_cfg:
    group: "benchmark"