jax_env: False
env_id: "LiftCube-v0"
seed: 0
algo: sac
sac:
  num_seed_steps: 10_000
  num_train_steps: 1_000_000
  replay_buffer_capacity: 1_000_000
  batch_size: 256
  num_envs: 1
  steps_per_env: 1
  grad_updates_per_step: 1

  eval_freq: 20_000
  eval_steps: 1000
  num_eval_envs: 4

  log_freq: 1000
  save_freq: 100_000

  learnable_temp: True
  initial_temperature: 1.0

  max_episode_length: 1000
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"