env_id: ant
jax_env: True

jax_platform_name: gpu

seed: 0

ppo:
  gamma: 0.95
  ent_coef: 1e-2
  
model:
  actor_lr: 3e-4
  critic_lr: 4e-4
 

train:
  num_envs: 32
  batch_size: 8192
  update_iters: 20
  epochs: 200
  steps_per_epoch: 1000


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "ppo/ant"
  wandb_cfg:
    group: "benchmark"