jax_env: False

jax_platform_name: gpu

seed: 0

ppo:
  num_envs: 8
  batch_size: 8192
  update_iters: 32
  steps_per_epoch: 1000
  gamma: 0.95
  ent_coef: 1e-2
  reset_env: True
  
model:
  actor_lr: 3e-4
  critic_lr: 4e-4

train:
  epochs: 1000

eval:
  num_eval_envs: 8
  steps_per_env: 1000 # one episode each
  eval_freq: 20


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"