jax_env: False

seed: 0
algo: ppo

# Environment configuration
env:
  env_id: "HalfCheetah-v2"
  max_episode_steps: 1000
eval_env:
  max_episode_steps: 1000

ppo:
  batch_size: 64
  num_envs: 1
  steps_per_env: 2048
  grad_updates_per_step: 320 # 10 epochs
  reset_env: False

  target_kl: 999
  discount: 0.99
  gae_lambda: 0.95
  ent_coef: 1e-2

  eval_freq: 1_000_000
  eval_steps: 1_000
  num_eval_envs: 4

  log_freq: 1_000
  save_freq: -1
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

train:
  steps: 10_000_000

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"