jax_env: False

seed: 0
algo: ppo

# Environment configuration
env:
  env_id: None
  max_episode_steps: 100
eval_env:
  max_episode_steps: 200

# Algorithm configurations
ppo:
  num_envs: 8
  batch_size: 400
  update_iters: 32
  steps_per_epoch: 400
  gamma: 0.95
  gae_lambda: 0.95
  ent_coef: 0
  reset_env: True

  eval_freq: 20_000
  eval_steps: 1000
  num_eval_envs: 4

  log_freq: 1000
  save_freq: 100_000

# Model configs
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

# Training time parameters
train:
  epochs: 1000

# Evaluation settings
eval:
  num_eval_envs: 8
  steps_per_env: 1000 # one episode each
  eval_freq: 20


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"