jax_env: False

seed: 0
algo: ppo

# Environment configuration
env:
  env_id: None
  max_episode_steps: 100
  env_kwargs:
    control_mode: "pd_ee_delta_pose"
eval_env:
  max_episode_steps: 200

# Algorithm configurations
ppo:
  num_envs: 8
  batch_size: 400
  update_iters: 200
  steps_per_epoch: 400
  gamma: 0.85
  gae_lambda: 0.95
  target_kl: 0.05
  ent_coef: 0
  reset_env: True

  eval_freq: 10 
  eval_steps: 200
  num_eval_envs: 4

  log_freq: 1000
  save_freq: 100_000

# Model configs
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

# Training time parameters
train:
  epochs: 1000

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"