jax_env: False

seed: 0
algo: sac

# Environment configuration
env:
  env_id: "PickCube-v0"
  max_episode_steps: 100
  env_kwargs:
    control_mode: "pd_ee_delta_pose"
eval_env:
  max_episode_steps: 200

sac:
  num_seed_steps: 4_000
  replay_buffer_capacity: 1_000_000
  batch_size: 1024
  num_envs: 4
  steps_per_env: 16
  grad_updates_per_step: 32

  discount: 0.8
  tau: 0.01
  backup_entropy: False

  eval_freq: 1000
  eval_steps: 200
  num_eval_envs: 4

  log_freq: 100
  save_freq: 1000

  learnable_temp: True
  initial_temperature: 1.0
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

train: 
  steps: 250_000

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "maniskill2_benchmark"