env_id: ant
jax_env: True
auto_reset: True

jax_platform_name: gpu

seed: 0

ppo:
  num_envs: 2048
  batch_size: 8192
  update_iters: 32
  steps_per_epoch: 16
  gamma: 0.95
  ent_coef: 1e-2
  reset_env: False

  num_eval_envs: 16
  eval_steps: 1000 # one episode each
  eval_freq: 20
  
model:
  actor_lr: 3e-4
  critic_lr: 4e-4
 

train:
  epochs: 1000

logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  exp_name: "ppo/ant_short"
  wandb_cfg:
    group: "benchmark"