jax_env: False

seed: 0
algo: ppo
# Algorithm configurations
ppo:
  num_envs: 1
  batch_size: 64
  update_iters: 320
  steps_per_epoch: 2048
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0
  reset_env: True

  eval_freq: 20_000
  eval_steps: 1000
  num_eval_envs: 4

  log_freq: 1000
  save_freq: 100_000
  
model:
  actor_lr: 3e-4
  critic_lr: 3e-4

# Training time parameters
train:
  epochs: 1000

eval:
  num_eval_envs: 8
  steps_per_env: 1000 # one episode each
  eval_freq: 20


logger:
  tensorboard: True
  wandb: False

  workspace: "robojax_exps"
  project_name: "robojax"
  wandb_cfg:
    group: "benchmark"